# Generated by Django 4.2.5 on 2023-11-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="picture_1",
            field=models.ImageField(null=True, upload_to="", verbose_name="帖子图片1"),
        ),
        migrations.AddField(
            model_name="post",
            name="picture_2",
            field=models.ImageField(null=True, upload_to="", verbose_name="帖子图片2"),
        ),
        migrations.AddField(
            model_name="post",
            name="picture_3",
            field=models.ImageField(null=True, upload_to="", verbose_name="帖子图片3"),
        ),
        migrations.AddField(
            model_name="post",
            name="picture_4",
            field=models.ImageField(null=True, upload_to="", verbose_name="帖子图片4"),
        ),
        migrations.AddField(
            model_name="post",
            name="picture_5",
            field=models.ImageField(null=True, upload_to="", verbose_name="帖子图片5"),
        ),
        migrations.AddField(
            model_name="post",
            name="picture_6",
            field=models.ImageField(null=True, upload_to="", verbose_name="帖子图片6"),
        ),
        migrations.AddField(
            model_name="post",
            name="picture_7",
            field=models.ImageField(null=True, upload_to="", verbose_name="帖子图片7"),
        ),
        migrations.AddField(
            model_name="post",
            name="picture_8",
            field=models.ImageField(null=True, upload_to="", verbose_name="帖子图片8"),
        ),
        migrations.AddField(
            model_name="post",
            name="picture_9",
            field=models.ImageField(null=True, upload_to="", verbose_name="帖子图片9"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(max_length=5000, null=True, verbose_name="帖子文字内容"),
        ),
    ]
