# Generated by Django 4.2.5 on 2023-11-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="帖子id"
            ),
        ),
    ]
