# Generated by Django 4.2.5 on 2023-12-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orthodonticcheckin',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
