# Generated by Django 4.2.5 on 2023-11-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        null=True,
                        verbose_name="小程序用户唯一id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        null=True,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(0, "未知"), (1, "男"), (2, "女")],
                        default=0,
                        verbose_name="性别",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        null=True,
                        verbose_name="电子邮箱",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=11,
                        null=True,
                        verbose_name="电话",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="生日"),
                ),
                (
                    "introduce",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        null=True,
                        verbose_name="个人简介",
                    ),
                ),
                ("user_image", models.CharField(max_length=200, verbose_name="用户头像")),
                (
                    "user_image_local",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to="user/%Y/%m/%d",
                        verbose_name="用户头像(本地)",
                    ),
                ),
                (
                    "register_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="是否有管理员权限"),
                ),
                (
                    "school_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        null=True,
                        verbose_name="学号",
                    ),
                ),
                (
                    "true_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        null=True,
                        verbose_name="真实姓名",
                    ),
                ),
            ],
            options={"verbose_name": "用户", "verbose_name_plural": "用户",},
        ),
    ]
