# Generated by Django 4.2.5 on 2023-12-02 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, null=True, verbose_name='用户id(wx分配)')),
                ('nickname', models.CharField(default='微信用户', max_length=50, null=True, verbose_name='用户名')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '其他')], default=0, null=True, verbose_name='性别')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='电话')),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='电子邮箱')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='media/user_images/', verbose_name='用户头像')),
                ('introduce', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='个人简介')),
                ('is_doctor', models.BooleanField(default=False, verbose_name='是否为医生用户')),
                ('brace_total', models.IntegerField(default=0, null=True, verbose_name='牙套总数量')),
                ('brace_used', models.IntegerField(default=0, null=True, verbose_name='已佩戴牙套数量')),
                ('followup_date', models.DateField(blank=True, null=True, verbose_name='下次复诊日期')),
                ('post_count', models.IntegerField(default=0, verbose_name='发帖总数')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fans', models.ManyToManyField(related_name='粉丝列表', to='user.userprofile')),
                ('follow', models.ManyToManyField(related_name='关注列表', to='user.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='用户', to='user.user')),
            ],
        ),
    ]
