# Generated by Django 4.2.5 on 2023-12-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.CharField(blank=True, default='学硕博士', max_length=50, null=True, verbose_name='学位'),
        ),
        migrations.AddField(
            model_name='user',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='正畸预计结束日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='fans_list',
            field=models.ManyToManyField(related_name='粉丝列表', to='user.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='follow_list',
            field=models.ManyToManyField(related_name='关注列表', to='user.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, default='牙医生', max_length=50, null=True, verbose_name='医生实名'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, default='北京大学', max_length=50, null=True, verbose_name='毕业院校'),
        ),
        migrations.AddField(
            model_name='user',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='正畸起始日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, default='牙医', max_length=100, null=True, verbose_name='医生职称'),
        ),
    ]
