# Generated by Django 4.2.5 on 2023-11-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options_remove_user_birthday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="生日"),
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(
                blank=True, default="", max_length=30, null=True, verbose_name="电子邮箱"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="introduce",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="个人简介"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_doctor",
            field=models.BooleanField(default=False, verbose_name="是否为医生用户"),
        ),
        migrations.AddField(
            model_name="user",
            name="user_image",
            field=models.CharField(max_length=200, null=True, verbose_name="用户头像"),
        ),
    ]
