# Generated by Django 4.2.5 on 2023-11-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_brace_total_user_brace_used_user_followup_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.IntegerField(
                choices=[(0, "男"), (1, "女"), (2, "其他")],
                default=0,
                null=True,
                verbose_name="性别",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                default="微信用户", max_length=50, null=True, verbose_name="用户名"
            ),
        ),
    ]
