# Generated by Django 4.2.5 on 2023-11-16 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_user_image"),
    ]

    operations = [
        migrations.AlterModelTable(name="user", table="user",),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fans",
                    models.ManyToManyField(related_name="粉丝列表", to="user.userprofile"),
                ),
                (
                    "follow",
                    models.ManyToManyField(related_name="关注列表", to="user.userprofile"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="用户",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
