# Generated by Django 4.2.5 on 2023-11-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_user_table_userprofile"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="user_id",),
        migrations.AddField(
            model_name="user",
            name="openid",
            field=models.CharField(
                max_length=50, null=True, verbose_name="用户openid(wx分配)"
            ),
        ),
    ]
