# Generated by Django 4.2.5 on 2023-11-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_remove_user_user_id_user_openid"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="openid",),
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.CharField(max_length=50, null=True, verbose_name="用户id(wx分配)"),
        ),
    ]
