# Generated by Django 4.2.5 on 2023-11-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_remove_user_openid_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_image",
            field=models.ImageField(
                null=True, upload_to="media/user_images/", verbose_name="用户头像"
            ),
        ),
    ]
