# Generated by Django 4.2.5 on 2023-11-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_user_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="post_count",
            field=models.IntegerField(default=0, verbose_name="发帖总数"),
        ),
    ]
